version: '3.7'

services:

  # === -----------------------------
  gateway:
    build: gateway
    restart: unless-stopped
    depends_on:
      - deconcentrator
      - registry
      - database
    links:
      - deconcentrator
      - registry
      - database
    ports:
      - 3000:3000
    environment:
      - DECONCENTRATOR_ENDPOINT
      - REGISTRY_ENDPOINT
      - DATABASE_ENDPOINT=http://database:3000/users/find

  # === -----------------------------
  deconcentrator:
    build: deconcentrator-js
    restart: unless-stopped
    depends_on:
      - rasa
    links:
      - rasa
    ports:
      - 8338:8338
    environment:
      - RASA_ENDPOINT

  # === -----------------------------
  registry:
    build: registry
    restart: unless-stopped
    links:
      - mensa
      - weather
    ports:
      - 9922:3000
    environment:
      - MENSA_ENDPOINT
      - WETTER_ENDPOINT

  # === -----------------------------
  rasa:
    image: rasa/rasa:1.6.0-spacy-de
    restart: unless-stopped
    depends_on:
      - duckling
    ports:
      - 5005:5005
    volumes:
      - ./rasa/app:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"

  duckling:
    image: rasa/duckling:0.1.6.2
    restart: unless-stopped

  # === -----------------------------
  mongo:
    image: mongo:4.0.4
    restart: unless-stopped
    ports:
      - 27017:27017
    #      - 27018:27018
    #      - 27019:27019
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      # - mongodata:/data/db # needed for me to run container on Windows 10
      - .database:/data/db # For Mac/Linux

  database:
    build: database
    restart: unless-stopped
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 27000:3000
    environment:
      - MONGO_DB_ENDPOINT=mongodb://mongo:27017/users

  # === -----------------------------
  mensa:
    build: mensa_microservice
    restart: unless-stopped
    ports:
      - 9950:8000

  # === -----------------------------
  weather:
    build: weather_microservice
    restart: unless-stopped
    ports:
      - 9951:7000
    environment:
      - WEATHER_API_KEY

networks:
  default:
    external:
      name: beuthbot_network
