version: '3.7'

services:

  gateway:
    build: gateway
    restart: always
    depends_on:
      - deconcentrator
      - registry
      - database
    links:
      - deconcentrator
      - registry
      - database
    ports:
      - 3000:3000
    environment:
      - DECONCENTRATOR_ENDPOINT=http://deconcentrator:8338/message
      - REGISTRY_ENDPOINT=http://registry:3000/get-response
      - DATABASE_ENDPOINT=http://database:3000/users/find
      - USERMESSENGER_TOKEN=some_safe_token

  deconcentrator:
    build: deconcentrator-js
    restart: always
    links:
      - rasa
    environment:
      - RASA_ENDPOINT=http://rasa:5005/model/parse

  cats:
    build: cat_microservice
    restart: always
    ports:
      - 7001:7001
    environment:
      - CATS_APIKEY
      - CATS_PORT

  stt:
    build: stt_microservice
    restart: always
    ports:
      - 7002:7002
    environment:
      - STT_PORT=7002

  rasa:
    image: rasa/rasa:2.1.3-spacy-de
    restart: always
    depends_on:
      - duckling
    volumes:
      - ./rasa/app:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"

  duckling:
    image: rasa/duckling:0.1.6.5
    restart: always

  mongo:
    image: mongo:4.0.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      # - mongodata:/data/db # needed for me to run container on Windows 10
      - .database:/data/db # For Mac/Linux

  database:
    build: database
    restart: always
    links:
      - mongo
    environment:
      - MONGO_DB_ENDPOINT=mongodb://mongo:27017/users
      - MONGO_URI=mongodb://mongo:27017

  database_microservice:
    build: database_microservice
    restart: always
    links:
      - database
    environment:
      - DATABASE_ENDPOINT=http://database:3000

  registry:
    build: registry
    restart: always
    links:
      - mensa
      - weather
      - database_microservice
    environment:
      - MENSA_ENDPOINT=http://mensa:8000/meals
      - WETTER_ENDPOINT=http://weather:7000/weather
      - DATABASE_ENDPOINT=http://database_microservice:27016/database
      - CATS_ENDPOINT=http://cats:7001/cat

  mensa:
    build: mensa_microservice
    restart: always

  weather:
    build: weather_microservice
    restart: always
    environment:
      - WEATHER_API_KEY

networks:
  default:
    external:
      name: beuthbot_network
