version: '3.7'

services:

  gateway:
    build: gateway
    restart: always
    depends_on:
      - deconcentrator
      - registry
      - database
    links:
      - deconcentrator
      - registry
      - database
    ports:
      - 3000:3000
    environment:
      - DECONCENTRATOR_ENDPOINT=http://deconcentrator:8338/message
      - REGISTRY_ENDPOINT=http://registry:3000/get-response
      - DATABASE_ENDPOINT=http://database:3000/users/find
    # networks:
    #   - beuthbot

  deconcentrator:
    build: deconcentrator-js
    restart: always
    depends_on:
      - rasa
    links:
      - rasa
    ports:
      - 8338:8338
    environment:
      - RASA_ENDPOINT=http://rasa:5005/model/parse
      - MIN_CONFIDENCE_SCORE=0.85
    # networks:
    #   - beuthbot

  rasa:
    image: rasa/rasa:1.6.0-spacy-de
    restart: always
    depends_on:
      - duckling
    ports:
      - 5005:5005
    volumes:
      - ./rasa/app:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    # networks:
    #   - beuthbot

  duckling:
    image: rasa/duckling:0.1.6.2
    restart: always
    # networks:
    #   - beuthbot

  mongo:
    image: mongo:4.0.4
    restart: always
    ports:
      - 27017:27017
    #      - 27018:27018
    #      - 27019:27019
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongodata:/data/db # needed for me to run container on Windows 10
      # - .database:/data/db # For Mac/Linux
    # networks:
    #   - beuthbot

  database:
    build: database
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 27000:3000
    environment:
      - MONGO_DB_ENDPOINT=mongodb://mongo:27017/users
      - MONGO_URI=mongodb://mongo:27017
    # networks:
    #   - beuthbot

  database_microservice:
    build: database_microservice
    restart: always
    depends_on:
      - database
    links:
      - database
    ports:
      - 27016:27016
    environment:
      - DATABASE_ENDPOINT=http://database:3000
    # networks:
    #   - beuthbot

  registry:
    build: registry
    restart: always
    links:
      - mensa
      - weather
      - database_microservice
    ports:
      - 9922:3000
    environment:
      - MENSA_ENDPOINT=http://mensa:8000/meals
      - WETTER_ENDPOINT=http://weather:7000/weather
      - DATABASE_ENDPOINT=http://database_microservice:27016/database
      - CATS_ENDPOINT=http://cats:7001/cat
    # networks:
    #   - beuthbot

  mensa:
    build: mensa_microservice
    restart: always
    # networks:
    #   - beuthbot
    ports:
      - 9950:8000

  weather:
    build: weather_microservice
    restart: always
    # networks:
    #   - beuthbot
    ports:
      - 9951:7000
    environment:
      - WEATHER_API_KEY

  cats:
    build: cat_microservice
    restart: always
    ports:
      - 7001:7001
    environment:
      - CATS_APIKEY
      - CATS_PORT
     
  stt:
    build: stt_microservice
    restart: always
    ports:
      - 7002:7002
    environment:
      - PORT=7002

networks:
  # beuthbot: {}
  default:
    external:
      name: beuthbot_network
volumes:
  mongodata:
